In [ ]:
import pandas as pd
df=pd.read_csv("/content/BL-Flickr-Images-Book (1) (1).csv")
print(df.head())

   Identifier             Edition Statement      Place of Publication  \
0         206                           NaN                    London
1         216                           NaN  London; Virtue & Yorston
2         218                           NaN                    London
3         472                           NaN                    London
4         480  A new edition, revised, etc.                    London

  Date of Publication              Publisher  \
0         1879 [1878]       S. Tinsley & Co.
1                1868           Virtue & Co.
2                1869  Bradbury, Evans & Co.
3                1851          James Darling
4                1857   Wertheim & Macintosh

                                               Title     Author  \
0                  Walter Forbes. [A novel.] By A. A      A. A.
1  All for Greed. [A novel. The dedication signed...  A., A. A.
2  Love the Avenger. By the author of â€œAll for Gr...  A., A. A.
3  Welsh Sketches, chiefly ecclesiastical, to the...  A., E. S.
4  [The World in which I live, and my place in it...  A., E. S.

                                   Contributors  Corporate Author  \
0                               FORBES, Walter.               NaN
1  BLAZE DE BURY, Marie Pauline Rose - Baroness               NaN
2  BLAZE DE BURY, Marie Pauline Rose - Baroness               NaN
3                   Appleyard, Ernest Silvanus.               NaN
4                           BROOME, John Henry.               NaN

   Corporate Contributors Former owner  Engraver Issuance type  \
0                     NaN          NaN       NaN   monographic
1                     NaN          NaN       NaN   monographic
2                     NaN          NaN       NaN   monographic
3                     NaN          NaN       NaN   monographic
4                     NaN          NaN       NaN   monographic

                                          Flickr URL  \
0  http://www.flickr.com/photos/britishlibrary/ta...
1  http://www.flickr.com/photos/britishlibrary/ta...
2  http://www.flickr.com/photos/britishlibrary/ta...
3  http://www.flickr.com/photos/britishlibrary/ta...
4  http://www.flickr.com/photos/britishlibrary/ta...

                            Shelfmarks
0    British Library HMNTS 12641.b.30.
1    British Library HMNTS 12626.cc.2.
2    British Library HMNTS 12625.dd.1.
3  British Library HMNTS 10369.bbb.15.
4     British Library HMNTS 9007.d.28.

In [ ]:
df.shape

(8287, 15)

In [ ]:
df.size

124305

In [ ]:
df.tail

,Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
8282,4158088,NaN,London,1838,NaN,"The Parochial History of Cornwall, founded on,...","GIDDY, afterwards GILBERT, Davies.","BOASE, Henry Samuel.|HALS, William.|LYSONS, Da...",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
8283,4158128,NaN,Derby,"1831, 32",M. Mozley & Son,The History and Gazetteer of the County of Der...,"GLOVER, Stephen - of Derby","NOBLE, Thomas.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
8284,4159563,NaN,London,[1806]-22,T. Cadell and W. Davies,Magna Britannia; being a concise topographical...,"LYSONS, Daniel - M.A., F.R.S., and LYSONS (Sam...","GREGSON, Matthew.|LYSONS, Samuel - F.R.S",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 19...
8285,4159587,NaN,Newcastle upon Tyne,1834,Mackenzie & Dent,"An historical, topographical and descriptive v...","Mackenzie, E. (Eneas)","ROSS, M. - of Durham",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 10...
8286,4160339,NaN,London,1834-43,NaN,Collectanea Topographica et Genealogica. [Firs...,NaN,"BANDINEL, Bulkeley.|Nichols, John Gough",NaN,NaN,NaN,NaN,continuing,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS|British Library HMNTS 79...

In [ ]:
to_drop=['Date of Publication','Issuance type']
df.drop(to_drop,inplace=True,axis=1)
df.head()

,Identifier,Edition Statement,Place of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Flickr URL,Shelfmarks
0,206,NaN,London,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,NaN,London; Virtue & Yorston,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,NaN,London,"Bradbury, Evans & Co.",Love the Avenger. By the author of â€œAll for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,NaN,London,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,"A new edition, revised, etc.",London,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.

In [ ]:
new_col_names={'Author':'Author Details'}
df_renamed=df.rename(columns=new_col_names)

In [ ]:
df.rename(columns={'Author':'Author Details'},inplace=True)
print(df.tail(10))

      Identifier Edition Statement Place of Publication  \
8277     4117751               NaN             New York
8278     4117752               NaN               London
8279     4156359               NaN             New York
8280     4157746               NaN               London
8281     4157862               NaN  Newcastle-upon-Tyne
8282     4158088               NaN               London
8283     4158128               NaN                Derby
8284     4159563               NaN               London
8285     4159587               NaN  Newcastle upon Tyne
8286     4160339               NaN               London

                    Publisher  \
8277        John Wiley & Sons
8278           TruÌˆbner & Co.
8279      G. P. Putnam's Sons
8280   F. C. and J. Rivington
8281               T. Fordyce
8282                      NaN
8283          M. Mozley & Son
8284  T. Cadell and W. Davies
8285         Mackenzie & Dent
8286                      NaN

                                                  Title  \
8277  Third Appendix to the fifth edition of Dana's ...
8278  A System of Mineralogy ... Fifth edition, rewr...
8279  History of the People of the Netherlands ... T...
8280  The New Chronicles of England and France, in t...
8281  Local Records; or, Historical Register of rema...
8282  The Parochial History of Cornwall, founded on,...
8283  The History and Gazetteer of the County of Der...
8284  Magna Britannia; being a concise topographical...
8285  An historical, topographical and descriptive v...
8286  Collectanea Topographica et Genealogica. [Firs...

                                         Author Details  \
8277                                DANA, James Dwight.
8278                                DANA, James Dwight.
8279                                BLOK, Pieter Johan.
8280                                    FABYAN, Robert.
8281      FORDYCE, T. - Printer, of Newcastle-upon-Tyne
8282                 GIDDY, afterwards GILBERT, Davies.
8283                         GLOVER, Stephen - of Derby
8284  LYSONS, Daniel - M.A., F.R.S., and LYSONS (Sam...
8285                              Mackenzie, E. (Eneas)
8286                                                NaN

                                           Contributors  Corporate Author  \
8277                            DANA, Edward Salisbury.               NaN
8278      BRUSH, George Jarvis.|DANA, Edward Salisbury.               NaN
8279                  BIERSTADT, Oscar A.|PUTNAM, Ruth.               NaN
8280  ELLIS, Henry - Sir, Principal Librarian of the...               NaN
8281   SYKES, John - Bookseller, of Newcastle-upon-Tyne               NaN
8282  BOASE, Henry Samuel.|HALS, William.|LYSONS, Da...               NaN
8283                                     NOBLE, Thomas.               NaN
8284           GREGSON, Matthew.|LYSONS, Samuel - F.R.S               NaN
8285                               ROSS, M. - of Durham               NaN
8286            BANDINEL, Bulkeley.|Nichols, John Gough               NaN

      Corporate Contributors Former owner  Engraver  \
8277                     NaN          NaN       NaN
8278                     NaN          NaN       NaN
8279                     NaN          NaN       NaN
8280                     NaN          NaN       NaN
8281                     NaN          NaN       NaN
8282                     NaN          NaN       NaN
8283                     NaN          NaN       NaN
8284                     NaN          NaN       NaN
8285                     NaN          NaN       NaN
8286                     NaN          NaN       NaN

                                             Flickr URL  \
8277  http://www.flickr.com/photos/britishlibrary/ta...
8278  http://www.flickr.com/photos/britishlibrary/ta...
8279  http://www.flickr.com/photos/britishlibrary/ta...
8280  http://www.flickr.com/photos/britishlibrary/ta...
8281  http://www.flickr.com/photos/britishlibrary/ta...
8282  http://www.flickr.com/photos/britishlibrary/ta...
8283  http://www.flickr.com/photos/britishlibrary/ta...
8284  http://www.flickr.com/photos/britishlibrary/ta...
8285  http://www.flickr.com/photos/britishlibrary/ta...
8286  http://www.flickr.com/photos/britishlibrary/ta...

                                             Shelfmarks
8277                   British Library HMNTS 7106.h.13.
8278                  British Library HMNTS 07108.i.14.
8279  British Library HMNTS|British Library HMNTS 09...
8280  British Library HMNTS|British Library HMNTS 19...
8281  British Library HMNTS|British Library HMNTS 01...
8282  British Library HMNTS|British Library HMNTS 10...
8283  British Library HMNTS|British Library HMNTS 10...
8284  British Library HMNTS|British Library HMNTS 19...
8285  British Library HMNTS|British Library HMNTS 10...
8286  British Library HMNTS|British Library HMNTS 79...

In [ ]:
df.head(10)

,Identifier,Edition Statement,Place of Publication,Publisher,Title,Author Details,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Flickr URL,Shelfmarks
0,206,NaN,London,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,NaN,London; Virtue & Yorston,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,NaN,London,"Bradbury, Evans & Co.",Love the Avenger. By the author of â€œAll for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,NaN,London,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,"A new edition, revised, etc.",London,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.
5,481,"Fourth edition, revised, etc.",London,William Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9006.ee.10.
6,519,NaN,London,The Author,Lagonells. By the author of Darmayne (F. E. A....,"A., F. E.","ASHLEY, Florence Emily.",NaN,NaN,NaN,NaN,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12637.e.3.
7,667,NaN,"pp. 40. G. Bryan & Co: Oxford, 1898",NaN,"The Coming of Spring, and other poems. By J. A...","A., J.|A., J.","ANDREWS, J. - Writer of Verse",NaN,NaN,NaN,NaN,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 011652.g.73.
8,874,NaN,London],NaN,"A Warning to the inhabitants of England, and L...",RemaÊ¿.,"ADAMS, Mary.",NaN,NaN,NaN,NaN,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 11645.bb.42.
9,1143,NaN,London,NaN,A Satyr against Vertue. (A poem: supposed to b...,"A., T.","OLDHAM, John.",NaN,NaN,NaN,NaN,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 11602.ee.10.(2.)

In [ ]:
unwanted_characters=['[',',','-']
def clean_dates(item):
  dop= str(item.loc['Place of Publication'])
  if dop == 'nan' or dop[0] == '[':
    return np.NaN
  for character in unwanted_characters:
    if character in dop:
      character_index=dop.find(character)
      dop=dop[: character_index]
  return dop
df['Place of Publication']=df.apply(clean_dates,axis = 1)

In [ ]:
def clean_title(title):
  if title == 'nan':
    return 'NaN'
  if title[0] == '[':
    title = title[1: title.find(']')]
  if 'by' in title:
    title = title[:title.find('by')]
  elif 'By' in title:
    title=title [:title.find('By')]
  if '[' in title:
    title=title [:title.find('[')]
  title = title [:-2]
df['Title'] = df['Title'].apply(clean_title)
df.head()

,Identifier,Edition Statement,Place of Publication,Publisher,Title,Author Details,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Flickr URL,Shelfmarks
0,206,NaN,London,S. Tinsley & Co.,None,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,NaN,London; Virtue & Yorston,Virtue & Co.,None,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,NaN,London,"Bradbury, Evans & Co.",None,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,NaN,London,James Darling,None,"A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,"A new edition, revised, etc.",London,Wertheim & Macintosh,None,"A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.